# -*- coding: utf-8 -*-
"""ProyectoFinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r4dvV7x5m8clvD0hzFGDmUTw5Tj9iscb
"""

import os

os.makedirs("project/sequential", exist_ok=True)
os.makedirs("project/parallel", exist_ok=True)
os.makedirs("project/results", exist_ok=True)

import numpy as np

# Parámetros
N = 1000
days = 365
beta = 0.3
gamma = 0.05
mu = 0.01

S, I, R, D = 0, 1, 2, 3

np.random.seed(42)

grid = np.zeros((N, N), dtype=np.int8)

# Infectados iniciales
initial = 100
idx = np.random.choice(N*N, initial, replace=False)
grid.flat[idx] = I


def count_neighbors_fast(grid):
    infected = (grid == I).astype(int)

    # suma de vecinos usando shifts (MUCHO más rápido)
    neighbors = (
        np.roll(infected, 1, axis=0) +
        np.roll(infected, -1, axis=0) +
        np.roll(infected, 1, axis=1) +
        np.roll(infected, -1, axis=1) +
        np.roll(np.roll(infected, 1, axis=0), 1, axis=1) +
        np.roll(np.roll(infected, 1, axis=0), -1, axis=1) +
        np.roll(np.roll(infected, -1, axis=0), 1, axis=1) +
        np.roll(np.roll(infected, -1, axis=0), -1, axis=1)
    )

    return neighbors


def step_fast(grid):
    new = grid.copy()

    neighbors = count_neighbors_fast(grid)

    # Susceptibles → Infectados
    prob_infection = beta * neighbors / 8
    rand_inf = np.random.rand(N, N)

    infect_mask = (grid == S) & (rand_inf < prob_infection)
    new[infect_mask] = I

    # Infectados → Recuperados o Muertos
    rand_rec = np.random.rand(N, N)
    rand_die = np.random.rand(N, N)

    recover_mask = (grid == I) & (rand_rec < gamma)
    die_mask = (grid == I) & (rand_die < mu)

    new[recover_mask] = R
    new[die_mask] = D

    return new


# Simulación
for d in range(days):
    grid = step_fast(grid)
    if d % 50 == 0:
        print(f"Día {d} completado")

print("Simulación terminada 🚀")

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
from multiprocessing import Pool

N = 1000
days = 365
beta = 0.3
gamma = 0.05
mu = 0.01

S, I, R, D = 0, 1, 2, 3

np.random.seed(42)
grid = np.zeros((N, N), dtype=np.int8)

initial = 100
idx = np.random.choice(N*N, initial, replace=False)
grid.flat[idx] = I

def count_neighbors(grid, x, y):
    total = 0
    for dx in [-1,0,1]:
        for dy in [-1,0,1]:
            if dx==0 and dy==0:
                continue
            nx, ny = x+dx, y+dy
            if 0 <= nx < N and 0 <= ny < N:
                if grid[nx, ny] == I:
                    total += 1
    return total

def update_block(args):
    grid, start, end = args
    new_block = grid[start:end].copy()

    for i in range(start, end):
        for j in range(N):
            if grid[i,j] == S:
                inf = count_neighbors(grid,i,j)
                if np.random.rand() < beta * inf/8:
                    new_block[i-start,j] = I
            elif grid[i,j] == I:
                if np.random.rand() < mu:
                    new_block[i-start,j] = D
                elif np.random.rand() < gamma:
                    new_block[i-start,j] = R

    return new_block

def parallel_step(grid, nproc=4):
    chunk = N // nproc
    args = []
    for i in range(nproc):
        start = i*chunk
        end = (i+1)*chunk if i != nproc-1 else N
        args.append((grid,start,end))

    with Pool(nproc) as p:
        res = p.map(update_block,args)

    return np.vstack(res)

for d in range(days):
    grid = parallel_step(grid,4)

print("Paralelo terminado")

import time
import pandas as pd

cores = [1,2,4,8]
times = []

for c in cores:
    test = grid.copy()
    start = time.time()

    for _ in range(20):
        if c == 1:
            test = step_fast(test)
        else:
            test = parallel_step_fast(test, c)

    t = time.time() - start
    times.append(t)

df = pd.DataFrame({
    "cores": cores,
    "time": times,
    "speedup": [times[0]/t for t in times]
})

df.to_csv("project/results/times.csv", index=False)
df

import matplotlib.pyplot as plt

plt.plot(df["cores"], df["speedup"], marker='o')
plt.xlabel("Cores")
plt.ylabel("Speed-up")
plt.title("Strong Scaling")
plt.grid()
plt.savefig("project/results/speedup.png")
plt.show()

import matplotlib.animation as animation

fig = plt.figure()

def animate(i):
    plt.imshow(grid, cmap='viridis')
    plt.title(f"Day {i}")
    plt.axis('off')

ani = animation.FuncAnimation(fig, animate, frames=30)
ani.save("project/results/simulation.mp4")